# Generated by Django 4.2 on 2023-12-26 18:45

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.AutoField(db_column='IDbu', primary_key=True, serialize=False)),
                ('last_name', models.CharField(db_column='buLastName', max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(db_column='buFirstName', max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(db_column='buMiddleName', max_length=50, verbose_name='Отчество')),
                ('identifier', models.CharField(db_column='buIdentifier', default=users.models.make_identifier, max_length=15, unique=True, verbose_name='Идентификатор')),
                ('password', models.CharField(db_column='buPassword', max_length=128, verbose_name='Пароль')),
                ('type', models.CharField(blank=True, choices=[('Ученик', 'ученик'), ('Учитель', 'учитель'), ('Администратор', 'администратор')], db_column='buType', default='Ученик', max_length=15, verbose_name='Тип пользователя')),
                ('is_active', models.BooleanField(db_column='buIsActive', default=True)),
                ('is_admin', models.BooleanField(db_column='buIsAdmin', default=False)),
                ('is_staff', models.BooleanField(db_column='buIsStaff', default=False)),
                ('is_superuser', models.BooleanField(db_column='buIsSuperUser', default=False)),
                ('last_login', models.DateTimeField(db_column='buLastLogin')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'base_users',
                'managed': False,
                'default_related_name': 'users',
            },
        ),
        migrations.CreateModel(
            name='ProfileStudent',
            fields=[
                ('id', models.AutoField(db_column='IDst', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'db_table': 'students',
                'managed': False,
                'default_related_name': 'profile_students',
            },
        ),
        migrations.CreateModel(
            name='ProfileTeacher',
            fields=[
                ('id', models.AutoField(db_column='IDt', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'db_table': 'teachers',
                'managed': False,
                'default_related_name': 'teachers',
            },
        ),
    ]
