# Generated by Django 4.2 on 2023-06-01 06:18

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_baseuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='identifier',
            field=models.CharField(default=users.models.make_identifier, max_length=15, unique=True, verbose_name='Идентификатор'),
        ),
    ]
