# Generated by Django 4.2 on 2023-12-28 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_baseuser_options_alter_profilestudent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={'default_related_name': 'user', 'managed': False, 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Все пользователи'},
        ),
    ]
