# Generated by Django 4.2 on 2023-06-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_journal', '0012_alter_mark_value'),
        ('users', '0003_remove_baseuser_username_alter_baseuser_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileteacher',
            name='timetable',
            field=models.ManyToManyField(blank=True, to='class_journal.schedule'),
        ),
    ]
