# Generated by Django 4.2 on 2023-12-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedmark',
            options={'managed': False, 'verbose_name': 'Выставленная оценка', 'verbose_name_plural': 'Выставленные оценки'},
        ),
        migrations.AlterModelOptions(
            name='studyclass',
            options={'default_related_name': 'study_class', 'managed': False, 'verbose_name': 'Учебный класс', 'verbose_name_plural': 'Учебные классы'},
        ),
    ]
