# Generated by Django 4.2 on 2023-05-20 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('class_journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsclass',
            name='students',
            field=models.ManyToManyField(blank=True, to='users.profilestudent'),
        ),
        migrations.AddField(
            model_name='studentsclass',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='class_journal.subject'),
        ),
        migrations.AddField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profilestudent'),
        ),
        migrations.AddField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_journal.subject'),
        ),
    ]
