# Generated by Django 4.2 on 2023-06-01 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_journal', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectInSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='class_journal.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thu', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], max_length=3)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_journal.subjectinschedule')),
            ],
        ),
    ]
