# Generated by Django 4.2 on 2023-06-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_journal', '0003_subjectinschedule_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='subject',
        ),
        migrations.AddField(
            model_name='schedule',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='class_journal.subjectinschedule'),
        ),
    ]
