# Generated by Django 4.2 on 2024-01-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_journal', '0004_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRoom',
            fields=[
                ('id', models.AutoField(db_column='IDsr', primary_key=True, serialize=False)),
                ('number', models.IntegerField(db_column='srNumber', verbose_name='Номер кабинета')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'db_table': 'study_rooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.AutoField(db_column='IDtt', primary_key=True, serialize=False)),
                ('week_day', models.CharField(choices=[('Понедельник', 'понедельник'), ('Вторник', 'вторник'), ('Среда', 'среда'), ('Четверг', 'четверг'), ('Пятница', 'пятница'), ('Суббота', 'суббота')], db_column='ttWeekDay', max_length=11, verbose_name='День недели')),
                ('time_begin', models.TimeField(db_column='ttTimeBegin', verbose_name='Время начала урока')),
                ('time_end', models.TimeField(db_column='ttTimeEnd', verbose_name='Время конца урока')),
            ],
            options={
                'verbose_name': 'Элемент расписания',
                'verbose_name_plural': 'Расписание',
                'db_table': 'timetable',
                'managed': False,
                'default_related_name': 'timetable',
            },
        ),
        migrations.AlterModelOptions(
            name='classstudents',
            options={'default_related_name': 'students_class', 'managed': False, 'ordering': ('study_class', 'student'), 'verbose_name': 'Состав класса', 'verbose_name_plural': 'Состав класса'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'managed': False, 'ordering': ('date',), 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterModelOptions(
            name='studyclass',
            options={'default_related_name': 'study_class', 'managed': False, 'ordering': ('year_begin', 'number_grade'), 'verbose_name': 'Учебный класс', 'verbose_name_plural': 'Учебные классы'},
        ),
    ]
