# Generated by Django 4.2 on 2023-06-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_journal', '0004_remove_schedule_subject_schedule_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsclass',
            name='timetable',
            field=models.ManyToManyField(blank=True, to='class_journal.schedule'),
        ),
    ]
