# Generated by Django 4.2 on 2023-06-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_journal', '0005_studentsclass_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Понедельник', 'понедельник'), ('Вторник', 'вторник'), ('Среда', 'среда'), ('Четверг', 'четверг'), ('Пятница', 'пятница'), ('Суббота', 'суббота'), ('Воскресенье', 'воскресенье')], max_length=11),
        ),
    ]
