# Generated by Django 4.2 on 2023-06-02 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_journal', '0006_alter_schedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectinschedule',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class_journal.subject'),
        ),
    ]
