# Generated by Django 4.2 on 2023-06-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_journal', '0007_alter_subjectinschedule_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='value',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('Понедельник', 'понедельник'), ('Вторник', 'вторник'), ('Среда', 'среда'), ('Четверг', 'четверг'), ('Пятница', 'пятница'), ('Суббота', 'суббота')], max_length=11),
        ),
        migrations.RemoveField(
            model_name='studentsclass',
            name='marks',
        ),
        migrations.AddField(
            model_name='studentsclass',
            name='marks',
            field=models.ManyToManyField(blank=True, to='class_journal.mark'),
        ),
    ]
