# Generated by Django 4.2 on 2023-06-07 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_baseuser_username_alter_baseuser_identifier'),
        ('class_journal', '0009_alter_mark_date_alter_mark_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.profilestudent'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='value',
            field=models.IntegerField(blank=True, choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
