# Generated by Django 4.2 on 2023-06-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_journal', '0010_alter_mark_date_alter_mark_student_alter_mark_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
