# Generated by Django 4.2 on 2023-06-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_journal', '0012_alter_mark_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='value',
            field=models.IntegerField(blank=True, choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5')], default=2, null=True),
        ),
    ]
